// <auto-generated />
using System;
using Dependent.Example;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dependent.Migrations
{
    [DbContext(typeof(DependentContext))]
    [Migration("20201029154244_Dependent")]
    partial class Dependent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("Dependent.Example.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parent", "Dependent", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Dependent.Example.Parent", b =>
                {
                    b.OwnsMany("Dependent.Example.Child", "Children", b1 =>
                        {
                            b1.Property<Guid>("ParentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ChildName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ParentId", "Id");

                            b1.ToTable("Children", "Dependent", true);

                            b1.WithOwner()
                                .HasForeignKey("ParentId");
                        });

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
